import json

with open("data/standards.json", "r", encoding="utf-8") as f:
    standards = json.load(f)

existing_ids = {s["is_number"]: s for s in standards}

complementary_standards = [
    {
        "id": "IS_1554_Part1_1988",
        "is_number": "IS 1554 (Part 1):1988",
        "title": "PVC Insulated (Heavy Duty) Electric Cables - Part 1: For Working Voltages Up to and Including 1100 V",
        "year": 1988,
        "domain": "Electrical",
        "scope": "Specifies requirements for PVC insulated heavy duty armoured and unarmoured cables for electricity distribution up to 1100 V.",
        "status": "current",
        "supersedes": [],
        "superseded_by": None,
        "amendments": [{"number": "Amendment 5", "year": 2018, "description": "FRLS compliance updates"}],
        "normative_references": ["IS 8130:2013", "IS 5831:1984"],
        "test_methods": ["IS 10810:1984"],
        "safety_standards": ["IS 1255:1983"],
        "installation_standards": ["IS 1255:1983"],
        "related_standards": ["IS 694:2010", "IS 7098 (Part 1):1988"],
        "certification": ["BIS Scheme-I (ISI Mark)"],
        "technical_parameters": {"voltage": "1.1 kV", "insulation": "PVC Heavy Duty"},
        "keywords": ["pvc power cable", "armoured pvc cable", "heavy duty cable"]
    },
    {
        "id": "IS_8130_2013",
        "is_number": "IS 8130:2013",
        "title": "Conductors for Insulated Electric Cables and Flexible Cords - Specification",
        "year": 2013,
        "domain": "Electrical",
        "scope": "Specifies requirements for copper and aluminium conductors (Class 1 solid, Class 2 stranded, Class 5 flexible) in electric cables.",
        "status": "current",
        "supersedes": ["IS 8130:1984"],
        "superseded_by": None,
        "amendments": [],
        "normative_references": [],
        "test_methods": ["IS 10810 (Part 5):1984"],
        "safety_standards": [],
        "installation_standards": [],
        "related_standards": ["IS 694:2010", "IS 7098 (Part 1):1988"],
        "certification": ["Foundational standard for cable manufacturing"],
        "technical_parameters": {"resistance": "Max DC resistance at 20 deg C conforming to table 1-4"},
        "keywords": ["cable conductor", "copper conductor", "aluminium conductor", "conductor resistance"]
    },
    {
        "id": "IS_10810_1984",
        "is_number": "IS 10810:1984",
        "title": "Methods of Test for Cables (Parts 0 to 64)",
        "year": 1984,
        "domain": "Electrical",
        "scope": "Comprehensive multi-part testing procedures for cables: spark test, insulation resistance, high voltage test, flammability, tensile and elongation, aging test.",
        "status": "current",
        "supersedes": [],
        "superseded_by": None,
        "amendments": [{"number": "Amendment 2", "year": 2016, "description": "Addition of acid gas generation test"}],
        "normative_references": [],
        "test_methods": ["IS 10810:1984"],
        "safety_standards": [],
        "installation_standards": [],
        "related_standards": ["IS 694:2010", "IS 7098 (Part 1):1988"],
        "certification": ["Accredited test method standard for all BIS wire and cable licensing"],
        "technical_parameters": {"test_scope": "high voltage, spark testing, insulation resistance, flammability"},
        "keywords": ["cable test method", "spark test", "flame retardant test", "cable testing is 10810"]
    },
    {
        "id": "IS_4031_Part6_1988",
        "is_number": "IS 4031 (Part 6):1988",
        "title": "Methods of Physical Tests for Hydraulic Cement - Part 6: Determination of Compressive Strength of Hydraulic Cement Other than Masonry Cement",
        "year": 1988,
        "domain": "Civil",
        "scope": "Specifies procedure for determining compressive strength of hydraulic cement mortar cubes (70.6 mm cubes) tested at 3, 7, and 28 days.",
        "status": "current",
        "supersedes": [],
        "superseded_by": None,
        "amendments": [{"number": "Amendment 1", "year": 2019, "description": "Precision of standard Ennore sand proportions"}],
        "normative_references": ["IS 650:1991"],
        "test_methods": ["IS 4031 (Part 6):1988"],
        "safety_standards": [],
        "installation_standards": [],
        "related_standards": ["IS 269:2015", "IS 1489 (Part 1):2015"],
        "certification": ["Standard test method for cement certification"],
        "technical_parameters": {"mortar_cube": "70.6 mm cube", "curing": "27 ± 2 deg C water curing"},
        "keywords": ["cement compressive strength", "cement testing", "mortar cube test", "ennore sand test"]
    },
    {
        "id": "IS_13920_2016",
        "is_number": "IS 13920:2016",
        "title": "Ductile Design and Detailing of Reinforced Concrete Structures Subjected to Seismic Forces - Code of Practice",
        "year": 2016,
        "domain": "Civil",
        "scope": "Covers requirements for ductile detailing of reinforced concrete structures in seismic zones III, IV, and V, including beam-column joints, confinement stirrups, and lap splicing.",
        "status": "current",
        "supersedes": ["IS 13920:1993"],
        "superseded_by": None,
        "amendments": [],
        "normative_references": ["IS 456:2000", "IS 1786:2008"],
        "test_methods": [],
        "safety_standards": ["IS 13920:2016"],
        "installation_standards": ["IS 13920:2016"],
        "related_standards": ["IS 456:2000", "IS 1786:2008"],
        "certification": ["Mandatory National Building Code earthquake safety compliance"],
        "technical_parameters": {"seismic_zones": ["Zone III", "Zone IV", "Zone V"], "rebar_grades": ["Fe 415D", "Fe 500D", "Fe 550D"]},
        "keywords": ["ductile detailing", "earthquake resistant", "seismic design", "beam column joint", "is 13920"]
    },
    {
        "id": "IS_10500_2012",
        "is_number": "IS 10500:2012",
        "title": "Drinking Water - Specification (Second Revision)",
        "year": 2012,
        "domain": "Civil/Environmental",
        "scope": "Prescribes requirements and methods of sampling and test for drinking water (potable water) supplied through public distribution systems or bottled sources.",
        "status": "current",
        "supersedes": ["IS 10500:1991"],
        "superseded_by": None,
        "amendments": [{"number": "Amendment 2", "year": 2021, "description": "Stringent pesticide and heavy metal limits"}],
        "normative_references": ["IS 3025 (Part 1 to 60)"],
        "test_methods": ["IS 3025"],
        "safety_standards": ["IS 10500:2012"],
        "installation_standards": [],
        "related_standards": ["IS 4984:2016", "IS 1239 (Part 1):2004"],
        "certification": ["Statutory standard for drinking water quality in India"],
        "technical_parameters": {"ph": "6.5 to 8.5", "tds": "< 500 mg/l acceptable, < 2000 permissible", "turbidity": "< 1 NTU"},
        "keywords": ["drinking water", "potable water standard", "water quality parameters", "is 10500"]
    },
    {
        "id": "IS_10028_Part2_1981",
        "is_number": "IS 10028 (Part 2):1981",
        "title": "Code of Practice for Selection, Installation and Maintenance of Transformers - Part 2: Installation",
        "year": 1981,
        "domain": "Electrical",
        "scope": "Provides guidelines on the foundations, plinth, fire protection barriers, oil soak pits, cabling, earthing, and commissioning tests for distribution and power transformers.",
        "status": "current",
        "supersedes": [],
        "superseded_by": None,
        "amendments": [],
        "normative_references": ["IS 3043:2018", "IS 2026:2011"],
        "test_methods": [],
        "safety_standards": ["IS 10028:1981", "IS 3043:2018"],
        "installation_standards": ["IS 10028 (Part 2):1981"],
        "related_standards": ["IS 1180 (Part 1):2014"],
        "certification": [],
        "technical_parameters": {"scope": "transformer installation, oil soak pit, blast walls"},
        "keywords": ["transformer installation", "transformer foundation", "substation installation", "soak pit transformer"]
    },
    {
        "id": "IS_8623_Part1_1993",
        "is_number": "IS 8623 (Part 1):1993",
        "title": "Low-Voltage Switchgear and Controlgear Assemblies - Part 1: Requirements for Type-Tested and Partially Type-Tested Assemblies (TTA/PTTA)",
        "year": 1993,
        "domain": "Electrical",
        "scope": "Applies to low-voltage switchgear and controlgear assemblies (PCC, MCC, distribution switchboards) with rated voltage not exceeding 1000 V AC or 1500 V DC.",
        "status": "current",
        "supersedes": ["IS 8623:1977"],
        "superseded_by": None,
        "amendments": [{"number": "Amendment 2", "year": 2018, "description": "Form 4b separation criteria and internal arc resistance"}],
        "normative_references": ["IS/IEC 60947-2:2016"],
        "test_methods": ["IS 8623 (Part 1):1993"],
        "safety_standards": ["IS 8623 (Part 1):1993"],
        "installation_standards": ["IS 732:2019"],
        "related_standards": ["IS/IEC 60947-2:2016", "IS/IEC 60947-4-1:2012"],
        "certification": ["BIS Scheme-I (ISI Mark)"],
        "technical_parameters": {"voltage": "up to 1000 V AC", "busbar_short_circuit": "up to 65 kA for 1 sec", "forms_of_separation": ["Form 1", "Form 2", "Form 3b", "Form 4b"]},
        "keywords": ["switchgear assembly", "motor control center", "mcc panel", "pcc panel", "distribution panel", "tta panel"]
    },
    {
        "id": "IS_IEC_60947_4_1_2012",
        "is_number": "IS/IEC 60947-4-1:2012",
        "title": "Low-Voltage Switchgear and Controlgear - Part 4: Contactors and Motor-Starters - Section 1: Electromechanical Contactors and Motor-Starters",
        "year": 2012,
        "domain": "Electrical",
        "scope": "Applies to contactors and motor starters (DOL, Star-Delta, auto-transformer starters) intended for switching electric motors and equipment up to 1000 V AC.",
        "status": "current",
        "supersedes": ["IS 13947 (Part 4/Sec 1):1993"],
        "superseded_by": None,
        "amendments": [],
        "normative_references": ["IS/IEC 60947-1:2007"],
        "test_methods": ["IS/IEC 60947-4-1:2012"],
        "safety_standards": ["IS/IEC 60947-4-1:2012"],
        "installation_standards": ["IS 8623 (Part 1):1993"],
        "related_standards": ["IS 12615:2018", "IS/IEC 60947-2:2016"],
        "certification": ["BIS Scheme-I (ISI Mark) - Mandatory"],
        "technical_parameters": {"utilization_categories": ["AC-1", "AC-3 (squirrel cage motor starting/stopping)", "AC-4"], "rated_current": "9 A to 800 A"},
        "keywords": ["motor starter", "contactor", "ac3 contactor", "star delta starter", "dol starter", "overload relay"]
    },
    {
        "id": "IS_13252_Part1_2010",
        "is_number": "IS 13252 (Part 1):2010",
        "title": "Information Technology Equipment - Safety - Part 1: General Requirements",
        "year": 2010,
        "domain": "Electronics/IT",
        "scope": "Applies to mains-powered or battery-powered information technology equipment, including electrical business equipment and associated equipment with rated voltage not exceeding 600 V.",
        "status": "current",
        "supersedes": [],
        "superseded_by": None,
        "amendments": [{"number": "Amendment 2", "year": 2017, "description": "Battery safety and power adapter creepage distances"}],
        "normative_references": [],
        "test_methods": ["IS 13252 (Part 1):2010"],
        "safety_standards": ["IS 13252 (Part 1):2010"],
        "installation_standards": [],
        "related_standards": [],
        "certification": ["BIS Compulsory Registration Scheme (CRS) - Mandatory for IT equipment, laptops, servers, adapters"],
        "technical_parameters": {"equipment_types": ["laptops", "tablets", "power adapters", "servers", "scanners"]},
        "keywords": ["it equipment safety", "power adapter bis", "laptop safety standard", "crs registration it"]
    },
    {
        "id": "IS_1255_1983",
        "is_number": "IS 1255:1983",
        "title": "Code of Practice for Installation and Maintenance of Power Cables Up to and Including 33 kV Rating",
        "year": 1983,
        "domain": "Electrical",
        "scope": "Guidelines for laying, jointing, terminating, testing, and maintenance of underground power cables up to 33 kV.",
        "status": "current",
        "supersedes": [],
        "superseded_by": None,
        "amendments": [{"number": "Amendment 3", "year": 2014, "description": "Heat shrinkable jointing kits and trench depths"}],
        "normative_references": ["IS 7098 (Part 1 & 2)", "IS 3043:2018"],
        "test_methods": [],
        "safety_standards": ["IS 1255:1983", "IS 3043:2018"],
        "installation_standards": ["IS 1255:1983"],
        "related_standards": ["IS 7098 (Part 1):1988", "IS 7098 (Part 2):2011"],
        "certification": [],
        "technical_parameters": {"trench_depth": "0.75m for LT, 1.05m for 11kV, 1.2m for 33kV"},
        "keywords": ["cable laying", "underground cable installation", "cable jointing", "trench depth cable"]
    }
]

for s in complementary_standards:
    if s["is_number"] not in existing_ids:
        standards.append(s)

with open("data/standards.json", "w", encoding="utf-8") as f:
    json.dump(standards, f, indent=2)

print(f"Updated standards.json. Total standards: {len(standards)}")
